# Generated by Django 5.2.9 on 2026-02-06 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=50)),
                ('provider_sub', models.CharField(max_length=255)),
                ('provider_preferred_username', models.CharField(max_length=50)),
                ('bind_time', models.DateTimeField(auto_now_add=True)),
                ('local_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('provider_name', 'provider_sub')},
            },
        ),
    ]
