# Generated by Django 3.2.18 on 2023-08-17 12:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hexoweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=2147483647)),
                ('filename', models.TextField(max_length=2147483647)),
                ('path', models.TextField(max_length=2147483647)),
                ('date', models.FloatField()),
                ('front_matter', models.TextField(blank=True, default='{}', max_length=2147483647)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
