# Generated by Django 3.2.8 on 2021-10-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexoweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2147483647)),
                ('content', models.CharField(max_length=2147483647)),
            ],
        ),
    ]
