# Generated by Django 3.2.0 on 2025-01-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexoweb', '0002_postmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='deleteConfig',
            field=models.TextField(default='{}', max_length=2147483647),
        ),
    ]
