# Generated by Django 3.2.8 on 2021-10-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexoweb', '0002_settingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache',
            name='content',
            field=models.CharField(blank=True, max_length=2147483647),
        ),
        migrations.AlterField(
            model_name='settingmodel',
            name='content',
            field=models.CharField(blank=True, max_length=2147483647),
        ),
    ]
