# Generated by Django 5.2.9 on 2026-01-07 08:46
# Modified to fix MongoDB compatibility (issue #681)
#
# This migration defines helper functions to handle MongoDB-specific index creation.
# Database indexes may be created conditionally based on the active database backend.
#
# The intended index behavior is:
# - MongoDB: Only creates reverse indexes (-date, -time) since forward indexes
#            are automatically created by db_index=True
# - Other DBs: Only creates reverse indexes (forward indexes come from db_index=True)

from django.db import migrations, models


logger = logging.getLogger(__name__)


def add_reverse_text_indexes_if_supported(apps, schema_editor):
    from django.db.utils import DatabaseError

    ImageModel = apps.get_model('hexoweb', 'ImageModel')
    TalkModel = apps.get_model('hexoweb', 'TalkModel')
    indexes = [
        (ImageModel, models.Index(fields=['-date'], name='hexoweb_ima_date_dee9c4_idx')),
        (TalkModel, models.Index(fields=['-time'], name='hexoweb_tal_time_7eb94e_idx')),
    ]

    for model, index in indexes:
        try:
            schema_editor.add_index(model, index)
        except DatabaseError as exc:
            # Some backends (e.g. MySQL on TEXT/BLOB) cannot create these indexes.
            logger.warning("Skip creating index %s on %s due to backend limitation: %s", index.name, model._meta.db_table, exc)


def remove_reverse_text_indexes_if_present(apps, schema_editor):
    from django.db.utils import DatabaseError

    ImageModel = apps.get_model('hexoweb', 'ImageModel')
    TalkModel = apps.get_model('hexoweb', 'TalkModel')
    indexes = [
        (ImageModel, models.Index(fields=['-date'], name='hexoweb_ima_date_dee9c4_idx')),
        (TalkModel, models.Index(fields=['-time'], name='hexoweb_tal_time_7eb94e_idx')),
    ]

    for model, index in indexes:
        try:
            schema_editor.remove_index(model, index)
        except DatabaseError as exc:
            logger.warning("Skip removing index %s on %s because it is unavailable: %s", index.name, model._meta.db_table, exc)


class Migration(migrations.Migration):

    dependencies = [
        ('hexoweb', '0003_imagemodel_deleteconfig'),
    ]

    operations = [
        # AlterField operations (set db_index=True)
        migrations.AlterField(
            model_name='cache',
            name='name',
            field=models.TextField(max_length=2147483647),
        ),
        migrations.AlterField(
            model_name='custommodel',
            name='name',
            field=models.TextField(max_length=2147483647),
        ),
        migrations.AlterField(
            model_name='friendmodel',
            name='status',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='friendmodel',
            name='time',
            field=models.TextField(max_length=2147483647),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='name',
            field=models.TextField(max_length=2147483647),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='date',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='path',
            field=models.TextField(max_length=2147483647),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='status',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='settingmodel',
            name='name',
            field=models.TextField(max_length=2147483647),
        ),
        migrations.AlterField(
            model_name='statisticpv',
            name='url',
            field=models.URLField(db_index=True),
        ),
        migrations.AlterField(
            model_name='statisticuv',
            name='ip',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='talkmodel',
            name='time',
            field=models.TextField(db_index=True, max_length=2147483647),
        ),
        # Add only reverse indexes (forward indexes come from db_index=True)
        migrations.AddIndex(
            model_name='imagemodel',
            index=models.Index(fields=['-date'], name='hexoweb_ima_date_dee9c4_idx'),
        ),
        migrations.AddIndex(
            model_name='postmodel',
            index=models.Index(fields=['-date'], name='hexoweb_pos_date_38e4f3_idx'),
        ),
        migrations.AddIndex(
            model_name='talkmodel',
            index=models.Index(fields=['-time'], name='hexoweb_tal_time_7eb94e_idx'),
        ),
    ]
