# Generated by Django 5.2.9 on 2026-01-07 08:46
# Modified to fix MongoDB compatibility (issue #681)
#
# IMPORTANT: This migration detects MongoDB by checking the database backend ENGINE configuration.
# It checks DATABASES['default']['ENGINE'] setting which supports both environment variables 
# and local configs.py deployments.
#
# The migration creates different indexes based on the database backend:
# - MongoDB: Only creates reverse indexes (-date, -time) since forward indexes 
#            are automatically created by db_index=True
# - Other DBs: Creates all explicit indexes for compatibility

from django.db import migrations, models


def _detect_mongodb_backend():
    """
    Detect if MongoDB is being used by checking the database backend ENGINE setting.
    
    This function checks the DATABASES configuration to determine the backend,
    which works with both environment-based and local config.py deployments.
    """
    try:
        from django.conf import settings
        if settings.configured:
            db_engine = settings.DATABASES.get('default', {}).get('ENGINE', '')
            return 'mongodb' in db_engine.lower()
    except Exception:
        # If settings are not configured, we can't determine the backend
        # Return False as a safe default (will create all indexes)
        pass
    
    return False


def get_conditional_operations():
    """
    Generate migration operations based on database backend.
    
    This detects the database backend at import time to determine which indexes
    to create. The operations list must be available at import time, so we check
    the database configuration from settings.
    """
    use_mongodb = _detect_mongodb_backend()
    
    # Base operations (AlterField with db_index=True)
    base_ops = [
        migrations.AlterField(
            model_name='cache',
            name='name',
            field=models.TextField(db_index=True, max_length=2147483647),
        ),
        migrations.AlterField(
            model_name='custommodel',
            name='name',
            field=models.TextField(db_index=True, max_length=2147483647),
        ),
        migrations.AlterField(
            model_name='friendmodel',
            name='status',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='friendmodel',
            name='time',
            field=models.TextField(db_index=True, max_length=2147483647),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='name',
            field=models.TextField(db_index=True, max_length=2147483647),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='date',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='path',
            field=models.TextField(db_index=True, max_length=2147483647),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='status',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='settingmodel',
            name='name',
            field=models.TextField(db_index=True, max_length=2147483647),
        ),
        migrations.AlterField(
            model_name='statisticpv',
            name='url',
            field=models.URLField(db_index=True),
        ),
        migrations.AlterField(
            model_name='statisticuv',
            name='ip',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='talkmodel',
            name='time',
            field=models.TextField(db_index=True, max_length=2147483647),
        ),
    ]
    
    # Add explicit indexes based on database backend
    if not use_mongodb:
        # For non-MongoDB databases, create all indexes explicitly
        base_ops.extend([
            migrations.AddIndex(
                model_name='cache',
                index=models.Index(fields=['name'], name='hexoweb_cac_name_393d54_idx'),
            ),
            migrations.AddIndex(
                model_name='custommodel',
                index=models.Index(fields=['name'], name='hexoweb_cus_name_5ca240_idx'),
            ),
            migrations.AddIndex(
                model_name='friendmodel',
                index=models.Index(fields=['time'], name='hexoweb_fri_time_a9636e_idx'),
            ),
            migrations.AddIndex(
                model_name='friendmodel',
                index=models.Index(fields=['status'], name='hexoweb_fri_status_efb727_idx'),
            ),
            migrations.AddIndex(
                model_name='imagemodel',
                index=models.Index(fields=['name'], name='hexoweb_ima_name_6a60d9_idx'),
            ),
            migrations.AddIndex(
                model_name='imagemodel',
                index=models.Index(fields=['-date'], name='hexoweb_ima_date_dee9c4_idx'),
            ),
            migrations.AddIndex(
                model_name='postmodel',
                index=models.Index(fields=['path'], name='hexoweb_pos_path_3952f0_idx'),
            ),
            migrations.AddIndex(
                model_name='postmodel',
                index=models.Index(fields=['-date'], name='hexoweb_pos_date_38e4f3_idx'),
            ),
            migrations.AddIndex(
                model_name='postmodel',
                index=models.Index(fields=['status'], name='hexoweb_pos_status_989f04_idx'),
            ),
            migrations.AddIndex(
                model_name='settingmodel',
                index=models.Index(fields=['name'], name='hexoweb_set_name_3e7cb3_idx'),
            ),
            migrations.AddIndex(
                model_name='statisticpv',
                index=models.Index(fields=['url'], name='hexoweb_sta_url_a0e580_idx'),
            ),
            migrations.AddIndex(
                model_name='statisticuv',
                index=models.Index(fields=['ip'], name='hexoweb_sta_ip_b9eddf_idx'),
            ),
            migrations.AddIndex(
                model_name='talkmodel',
                index=models.Index(fields=['time'], name='hexoweb_tal_time_a7d991_idx'),
            ),
            migrations.AddIndex(
                model_name='talkmodel',
                index=models.Index(fields=['-time'], name='hexoweb_tal_time_7eb94e_idx'),
            ),
        ])
    else:
        # For MongoDB, only add reverse indexes (which can't be expressed by db_index=True)
        base_ops.extend([
            migrations.AddIndex(
                model_name='imagemodel',
                index=models.Index(fields=['-date'], name='hexoweb_ima_date_dee9c4_idx'),
            ),
            migrations.AddIndex(
                model_name='postmodel',
                index=models.Index(fields=['-date'], name='hexoweb_pos_date_38e4f3_idx'),
            ),
            migrations.AddIndex(
                model_name='talkmodel',
                index=models.Index(fields=['-time'], name='hexoweb_tal_time_7eb94e_idx'),
            ),
        ])
    
    return base_ops


class Migration(migrations.Migration):

    dependencies = [
        ('hexoweb', '0003_imagemodel_deleteconfig'),
    ]

    operations = get_conditional_operations()
