name: Docker Image Release CI

on:
  push:
    tags:
      - '*'

env:
  APP_NAME: Qexo
  DOCKERHUB_REPO: abudulin/qexo

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Update QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes -c yes
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Generate App Version
        run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: |
            linux/386
            linux/amd64
            linux/arm64
            linux/arm/v6
            linux/arm/v7
#            linux/ppc64le
#            linux/s390x  # wtf is this?
          push: true
          build-args: |
            APP_NAME=${{ env.APP_NAME }}
            APP_VERSION=${{ env.APP_VERSION }}
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}
